//! Traits for PDE spatial discretization backends.

use crate::{
    ode::ODE,
    traits::{Real, State},
};

/// Spatial discretization backend for a PDE.
///
/// Backends convert a continuous PDE definition into a semi-discrete ODE system
/// over the global state `Y`. Different backends can use the same PDE trait but
/// choose different spatial operators, such as finite differences, finite
/// volumes, staggered grids, or finite elements.
pub trait SpatialDiscretization<Eq, T, U, Y, const D: usize>
where
    T: Real,
    U: State<T>,
    Y: State<T>,
{
    /// Semi-discrete ODE system generated by this backend.
    type System: ODE<T, Y>;

    /// Convert `equation` into a semi-discrete ODE system.
    fn discretize(self, equation: Eq) -> Self::System;
}
